# Quick Recap of Python

Let us quickly recap of some of the core programming concepts of Python before we get into Spark.

## Data Engineering Life Cycle

Let us first understand the Data Engineering Life Cycle. We typically read the data, process it by applying business rules and write the data back to different targets
* Read the data from different sources.
  * Files
  * Databases
  * Mainframes
  * APIs
* Processing the data
  * Row Level Transformations
  * Aggregations
  * Sorting
  * Ranking
  * Joining multiple data sets
* Write data to different targets.
  * Files
  * Databases
  * Mainframes
  * APIs

## Python CLI or Jupyter Notebook

We can use Python CLI or Jupyter Notebook to explore APIs.
* We can launch Python CLI using `python` command.
* We can launch the Jupyter Notebook using the `jupyter notebook` command.
* A web service will be started on port number 8888 by default.
* We can go to the browser and connect to the web server using IP address and port number.
* We should be able to explore code in interactive fashion.
* We can issue magic commands such as %%sh to run shell commands, %%md to document using markdown etc.

### Tasks

Let us perform these tasks to just recollect how to use Python CLI or Jupyter Notebook.
* Create variables `i` and `j` assigning `10` and `20.5` respectively.

In [1]:
i = 10
j = 20.5

* Add the values and assign result to `res`.

In [2]:
res = i + j
print(str(res))

30.5

* Get the `type` of `i`, `j` and `res`.

In [3]:
type(i)

int

In [4]:
type(j)

float

In [5]:
type(res)

float

* Get the help on `int`.

In [6]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int(x=0) -> integer
 |  int(x, base=10) -> integer
 |
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __bool__(self, /)
 |      self != 0
 |
 |  __ceil__(...)
 |      Ceiling of an Integral returns itself.
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floor__(...)
 |      Flooring an Integral returns itself.
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(...)
 |      default object formatter
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getnewargs__(...)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __index__(self, /)
 |      Return self converted to an integer, if self is suitable for use as an index into a list.
 |
 |  __int__(self, /)
 |      int(self)
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lshift__(self, value, /)
 |      Return self<<value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __neg__(self, /)
 |      -self
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __pos__(self, /)
 |      +self
 |
 |  __pow__(self, value, mod=None, /)
 |      Return pow(self, value, mod).
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __rdivmod__(self, value, /)
 |      Return divmod(value, self).
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rfloordiv__(self, value, /)
 |      Return value//self.
 |
 |  __rlshift__(self, value, /)
 |      Return value<<self.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __round__(...)
 |      Rounding an Integral returns itself.
 |      Rounding with an ndigits argument also returns an integer.
 |
 |  __rpow__(self, value, mod=None, /)
 |      Return pow(value, self, mod).
 |
 |  __rrshift__(self, value, /)
 |      Return value>>self.
 |
 |  __rshift__(self, value, /)
 |      Return self>>value.
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __sizeof__(...)
 |      Returns size in memory, in bytes
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  __truediv__(self, value, /)
 |      Return self/value.
 |
 |  __trunc__(...)
 |      Truncating an Integral returns itself.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  bit_length(...)
 |      int.bit_length() -> int
 |
 |      Number of bits necessary to represent self in binary.
 |      >>> bin(37)
 |      '0b100101'
 |      >>> (37).bit_length()
 |      6
 |
 |  conjugate(...)
 |      Returns self, the complex conjugate of any int.
 |
 |  from_bytes(...) from builtins.type
 |      int.from_bytes(bytes, byteorder, *, signed=False) -> int
 |
 |      Return the integer represented by the given array of bytes.
 |
 |      The bytes argument must be a bytes-like object (e.g. bytes or bytearray).
 |
 |      The byteorder argument determines the byte order used to represent the
 |      integer.  If byteorder is 'big', the most significant byte is at the
 |      beginning of the byte array.  If byteorder is 'little', the most
 |      significant byte is at the end of the byte array.  To request the native
 |      byte order of the host system, use `sys.byteorder' as the byte order value.
 |
 |      The signed keyword-only argument indicates whether two's complement is
 |      used to represent the integer.
 |
 |  to_bytes(...)
 |      int.to_bytes(length, byteorder, *, signed=False) -> bytes
 |
 |      Return an array of bytes representing an integer.
 |
 |      The integer is represented using length bytes.  An OverflowError is
 |      raised if the integer is not representable with the given number of
 |      bytes.
 |
 |      The byteorder argument determines the byte order used to represent the
 |      integer.  If byteorder is 'big', the most significant byte is at the
 |      beginning of the byte array.  If byteorder is 'little', the most
 |      significant byte is at the end of the byte array.  To request the native
 |      byte order of the host system, use `sys.byteorder' as the byte order value.
 |
 |      The signed keyword-only argument determines whether two's complement is
 |      used to represent the integer.  If signed is False and a negative integer
 |      is given, an OverflowError is raised.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  denominator
 |      the denominator of a rational number in lowest terms
 |
 |  imag
 |      the imaginary part of a complex number
 |
 |  numerator
 |      the numerator of a rational number in lowest terms
 |
 |  real
 |      the real part of a complex number

* Get the help on `startswith` that is available on `str`.

In [7]:
help(str.startswith)

Help on method_descriptor:

startswith(...)
    S.startswith(prefix[, start[, end]]) -> bool

    Return True if S starts with the specified prefix, False otherwise.
    With optional start, test S beginning at that position.
    With optional end, stop comparing S at that position.
    prefix can also be a tuple of strings to try.

## Basic Programming Constructs

Let us recollect some of the basic programming constructs of Python.
* Comparison Operations (==, !=, <, >, <=, >=, etc) 
  * All the comparison operators return a True or False (Boolean value)
* Conditionals (if) 
  * We typically use comparison operators as part of conditionals.
* Loops (for) 
  * We can iterate through collection using `for i in l` where l is a standard collection such as list or set.
  * Python provides special function called as `range` which will return a collection of integers between the given range. It excludes the upper bound value.
* In Python, scope is defined by indentation.

### Tasks
 
Let us perform few tasks to quickly recap basic programming constructs of Python.
 * Get all the odd numbers between 1 and 15.

In [8]:
list(range(1, 16, 2))

[1, 3, 5, 7, 9, 11, 13, 15]

* Print all those numbers which are divisible by 3 from the above list.

In [9]:
for i in list(range(1, 16, 2)):
    if(i%3 == 0): print(i)

3
9
15

## Developing Functions

Let us understand how to develop functions using Python as programming language.
* Function starts with `def` followed by function name.
* Parameters can be of different types.
    * Required
    * Keyword
    * Variable Number
    * Functions
* Functions which take another function as an argument is called higher order functions.

### Tasks

Let us perform few tasks to understand how to develop functions in Python.   
* Sum of integers between lower bound and upper bound using formula.

In [10]:
def sumOfN(n):
    return int((n * (n + 1)) / 2)

In [11]:
sumOfN(10)

55

In [12]:
def sumOfIntegers(lb, ub):
    return sumOfN(ub) - sumOfN(lb -1)

In [13]:
sumOfIntegers(5, 10)

45

* Sum of integers between lower bound and upper bound using loops.

In [14]:
def sumOfIntegers(lb, ub):
    total = 0
    for e in range(lb, ub + 1):
        total += e
    return total

In [15]:
sumOfIntegers(1, 10)

55

* Sum of squares of integers between lower bound and upper bound using loops.

In [16]:
def sumOfSquares(lb, ub):
    total = 0
    for e in range(lb, ub + 1):
        total += e * e
    return total

In [17]:
sumOfSquares(2, 4)

29

* Sum of the even numbers between lower bound and upper bound using loops.

In [18]:
def sumOfEvens(lb, ub):
    total = 0
    for e in range(lb, ub + 1):
        total += e if e%2==0 else 0
    return total

In [19]:
sumOfEvens(2, 4)

6

## Lambda Functions

Let us recap details related to lambda functions.
* We can develop functions with out names. They are called Lambda Functions and also known as Anonymous Functions.
* We typically use them to pass as arguments to higher order functions which takes functions as arguments

### Tasks

Let us perform few tasks related to lambda functions.    
* Create a generic function mySum which is supposed to perform arithmetic using integers within a range.   
  * It takes 3 arguments - `lb`, `ub` and `f`.
  * Function f should be invoked inside the function on each element within the range.

In [20]:
def mySum(lb, ub, f):
    total = 0
    for e in range(lb, ub + 1):
        total += f(e)
    return total

* Sum of integers between lower bound and upper bound using `mySum`.

In [21]:
mySum(2, 4, lambda i: i)

9

* Sum of squares of integers between lower bound and upper bound using `mySum`.

In [22]:
mySum(2, 4, lambda i: i * i)

29

* Sum of the even numbers between lower bound and upper bound using `mySum`.

In [23]:
mySum(2, 4, lambda i: i if i%2 == 0 else 0)

6

## Overview of Collections

Let's quickly recap about Collections and Tuples in Python. We will primarily talk about collections that comes as part of Python standard library such as `list`, `set`, `dict` and `tuple`.
* Group of elements with length and index - `list`
* Group of unique elements - `set`
* Group of key value pairs - `dict`
* While `list` and `set` contain group of homogeneous elements, `dict` and `tuple` contains group of heterogeneous elements.
* `list` or `set` are analogous to a database table while `dict` or `tuple` are analogous to individual record.
* Typically we create list of tuples or dicts or set of tuples or dicts. Also a dict can be considered as list of pairs.
* We typically use Map Reduce APIs to process the data in collections. There are also some pre-defined functions such as `len`, `sum`, `min`, `max` etc for aggregating data in collections.

### Tasks

Let us perform few tasks to quickly recap details about Collections and Tuples in Python. We will also quickly recap about Map Reduce APIs.

* Create a collection of orders by reading data from a file.

In [24]:
%%sh

ls -ltr /data/retail_db/orders/part-00000

-rw-r--r-- 1 root root 2999944 Jan 21  2021 /data/retail_db/orders/part-00000

In [25]:
orders_path = "/data/retail_db/orders/part-00000"
orders = open(orders_path). \
    read(). \
    splitlines()

* Get all unique order statuses. Make sure data is sorted in alphabetical order.

In [26]:
# sorted(set(map(lambda o: o.split(",")[3], orders)))

* Get count of all unique dates.

In [27]:
len(list(map(lambda o: o.split(",")[1], orders)))

68883

* Sort the data in orders in ascending order by order_customer_id and then order_date.

In [28]:
sorted(orders, key=lambda k: (int(k.split(",")[2]), k.split(",")[1]))

['22945,2013-12-13 00:00:00.0,1,COMPLETE',
 '57963,2013-08-02 00:00:00.0,2,ON_HOLD',
 '15192,2013-10-29 00:00:00.0,2,PENDING_PAYMENT',
 '67863,2013-11-30 00:00:00.0,2,COMPLETE',
 '33865,2014-02-18 00:00:00.0,2,COMPLETE',
 '22646,2013-12-11 00:00:00.0,3,COMPLETE',
 '61453,2013-12-14 00:00:00.0,3,COMPLETE',
 '23662,2013-12-19 00:00:00.0,3,COMPLETE',
 '35158,2014-02-26 00:00:00.0,3,COMPLETE',
 '46399,2014-05-09 00:00:00.0,3,PROCESSING',
 '56178,2014-07-15 00:00:00.0,3,PENDING',
 '57617,2014-07-24 00:00:00.0,3,COMPLETE',
 '9023,2013-09-19 00:00:00.0,4,COMPLETE',
 '9704,2013-09-24 00:00:00.0,4,COMPLETE',
 '17253,2013-11-09 00:00:00.0,4,PENDING_PAYMENT',
 '37878,2014-03-15 00:00:00.0,4,COMPLETE',
 '49339,2014-05-28 00:00:00.0,4,COMPLETE',
 '51157,2014-06-10 00:00:00.0,4,CLOSED',
 '13705,2013-10-18 00:00:00.0,5,COMPLETE',
 '36472,2014-03-06 00:00:00.0,5,PROCESSING',
 '41333,2014-04-05 00:00:00.0,5,COMPLETE',
 '45832,2014-05-05 00:00:00.0,5,PENDING_PAYMENT',
 '7485,2013-09-09 00:00:00.0,6,PROCESSING',
 '7787,2013-09-10 00:00:00.0,6,PENDING',
 '22457,2013-12-10 00:00:00.0,6,PENDING_PAYMENT',
 '32895,2014-02-13 00:00:00.0,6,PENDING_PAYMENT',
 '9977,2013-09-25 00:00:00.0,7,PROCESSING',
 '61683,2013-12-22 00:00:00.0,7,COMPLETE',
 '26052,2014-01-02 00:00:00.0,7,PENDING_PAYMENT',
 '26730,2014-01-06 00:00:00.0,7,ON_HOLD',
 '62132,2014-01-09 00:00:00.0,7,ON_HOLD',
 '28539,2014-01-17 00:00:00.0,7,PENDING_PAYMENT',
 '35559,2014-03-01 00:00:00.0,7,PROCESSING',
 '39456,2014-03-26 00:00:00.0,7,PROCESSING',
 '7688,2013-09-10 00:00:00.0,8,PROCESSING',
 '8497,2013-09-16 00:00:00.0,8,CLOSED',
 '19801,2013-11-24 00:00:00.0,8,PENDING',
 '22297,2013-12-08 00:00:00.0,8,COMPLETE',
 '62064,2014-01-08 00:00:00.0,8,PENDING_PAYMENT',
 '29383,2014-01-22 00:00:00.0,8,COMPLETE',
 '65018,2014-04-27 00:00:00.0,8,PENDING_PAYMENT',
 '68507,2014-05-30 00:00:00.0,8,PENDING',
 '67610,2013-09-12 00:00:00.0,9,PENDING_PAYMENT',
 '12828,2013-10-12 00:00:00.0,9,COMPLETE',
 '18918,2013-11-19 00:00:00.0,9,PENDING_PAYMENT',
 '64753,2014-04-17 00:00:00.0,9,PENDING_PAYMENT',
 '50086,2014-06-03 00:00:00.0,9,COMPLETE',
 '54350,2014-07-03 00:00:00.0,9,CLOSED',
 '45239,2014-05-01 00:00:00.0,10,COMPLETE',
 '56133,2014-07-15 00:00:00.0,10,COMPLETE',
 '11811,2013-10-05 00:00:00.0,11,COMPLETE',
 '17625,2013-11-11 00:00:00.0,11,CLOSED',
 '42837,2014-04-16 00:00:00.0,11,PENDING_PAYMENT',
 '51781,2014-06-14 00:00:00.0,11,COMPLETE',
 '921,2013-07-30 00:00:00.0,12,PENDING_PAYMENT',
 '58919,2013-09-07 00:00:00.0,12,ON_HOLD',
 '59731,2013-10-10 00:00:00.0,12,CLOSED',
 '20537,2013-11-29 00:00:00.0,12,PENDING_PAYMENT',
 '24642,2013-12-25 00:00:00.0,12,PAYMENT_REVIEW',
 '36246,2014-03-04 00:00:00.0,12,PENDING_PAYMENT',
 '44131,2014-04-25 00:00:00.0,12,PROCESSING',
 '45831,2014-05-05 00:00:00.0,12,PENDING_PAYMENT',
 '2109,2013-08-05 00:00:00.0,13,COMPLETE',
 '10524,2013-09-27 00:00:00.0,13,ON_HOLD',
 '22725,2013-12-11 00:00:00.0,13,COMPLETE',
 '27702,2014-01-12 00:00:00.0,13,PROCESSING',
 '36217,2014-03-04 00:00:00.0,13,COMPLETE',
 '63963,2014-03-18 00:00:00.0,13,ON_HOLD',
 '58343,2013-08-17 00:00:00.0,14,PROCESSING',
 '9453,2013-09-22 00:00:00.0,14,COMPLETE',
 '20622,2013-11-29 00:00:00.0,14,COMPLETE',
 '21077,2013-12-01 00:00:00.0,14,CLOSED',
 '26976,2014-01-08 00:00:00.0,14,COMPLETE',
 '63552,2014-03-02 00:00:00.0,14,PENDING',
 '37854,2014-03-15 00:00:00.0,14,COMPLETE',
 '39208,2014-03-23 00:00:00.0,14,ON_HOLD',
 '66343,2014-06-15 00:00:00.0,14,PENDING_PAYMENT',
 '1559,2013-08-02 00:00:00.0,15,COMPLETE',
 '8252,2013-09-14 00:00:00.0,15,PENDING_PAYMENT',
 '27092,2014-01-09 00:00:00.0,15,COMPLETE',
 '48376,2014-05-21 00:00:00.0,15,COMPLETE',
 '191,2013-07-26 00:00:00.0,16,CLOSED',
 '19211,2013-11-21 00:00:00.0,16,PENDING_PAYMENT',
 '68759,2013-11-27 00:00:00.0,16,COMPLETE',
 '22858,2013-12-12 00:00:00.0,16,COMPLETE',
 '34997,2014-02-25 00:00:00.0,16,COMPLETE',
 '41831,2014-04-09 00:00:00.0,16,SUSPECTED_FRAUD',
 '43399,2014-04-20 00:00:00.0,16,COMPLETE',
 '789,2013-07-29 00:00:00.0,17,COMPLETE',
 '17053,2013-11-08 00:00:00.0,17,ON_HOLD',
 '30338,2014-01-29 00:00:00.0,17,CLOSED',
 '52604,2014-06-19 00:00:00.0,17,COMPLETE',
 '57733,2014-07-24 00:00:00.0,17,CLOSED',
 '3742,2013-08-15 00:00:00.0,18,COMPLETE',
 '6912,2013-09-06 00:00:00.0,18,CLOSED',
 '19709,2013-11-24 00:00:00.0,18,CANCELED',
 '24295,2013-12-22 00:00:00.0,18,COMPLETE',
 '27740,2014-01-12 00:00:00.0,18,COMPLETE',
 '27805,2014-01-13 00:00:00.0,18,COMPLETE',
 '49411,2014-05-29 00:00:00.0,18,COMPLETE',
 '53932,2014-06-30 00:00:00.0,18,PENDING_PAYMENT',
 '1018,2013-07-30 00:00:00.0,19,COMPLETE',
 '6122,2013-09-01 00:00:00.0,19,CLOSED',
 '12181,2013-10-07 00:00:00.0,19,COMPLETE',
 '16447,2013-11-05 00:00:00.0,19,CLOSED',
 '21640,2013-12-05 00:00:00.0,19,COMPLETE',
 '32079,2014-02-08 00:00:00.0,19,PENDING',
 '37228,2014-03-11 00:00:00.0,19,CLOSED',
 '45390,2014-05-02 00:00:00.0,19,PENDING_PAYMENT',
 '54623,2014-07-05 00:00:00.0,19,PROCESSING',
 '5101,2013-08-25 00:00:00.0,20,COMPLETE',
 '8169,2013-09-14 00:00:00.0,20,PENDING_PAYMENT',
 '15199,2013-10-29 00:00:00.0,20,COMPLETE',
 '21533,2013-12-04 00:00:00.0,20,PENDING_PAYMENT',
 '24792,2013-12-25 00:00:00.0,20,COMPLETE',
 '34268,2014-02-20 00:00:00.0,20,CLOSED',
 '57269,2014-07-21 00:00:00.0,20,PROCESSING',
 '16646,2013-11-06 00:00:00.0,21,COMPLETE',
 '25802,2013-12-31 00:00:00.0,21,PENDING_PAYMENT',
 '33481,2014-02-16 00:00:00.0,21,PENDING',
 '56977,2014-07-20 00:00:00.0,21,PROCESSING',
 '1995,2013-08-04 00:00:00.0,22,CLOSED',
 '5683,2013-08-29 00:00:00.0,22,PROCESSING',
 '10479,2013-09-27 00:00:00.0,22,COMPLETE',
 '23721,2013-12-19 00:00:00.0,22,PENDING',
 '47800,2014-05-16 00:00:00.0,22,COMPLETE',
 '50663,2014-06-07 00:00:00.0,22,PENDING_PAYMENT',
 '6521,2013-09-04 00:00:00.0,23,SUSPECTED_FRAUD',
 '7050,2013-09-07 00:00:00.0,23,CLOSED',
 '11317,2013-10-03 00:00:00.0,23,PENDING_PAYMENT',
 '22434,2013-12-09 00:00:00.0,23,CLOSED',
 '23432,2013-12-17 00:00:00.0,23,PROCESSING',
 '32638,2014-02-11 00:00:00.0,23,PENDING_PAYMENT',
 '33441,2014-02-16 00:00:00.0,23,PENDING_PAYMENT',
 '42824,2014-04-15 00:00:00.0,23,PROCESSING',
 '2167,2013-08-06 00:00:00.0,24,PENDING_PAYMENT',
 '17316,2013-11-09 00:00:00.0,24,COMPLETE',
 '27877,2014-01-13 00:00:00.0,24,SUSPECTED_FRAUD',
 '30282,2014-01-29 00:00:00.0,24,PENDING',
 '39809,2014-03-28 00:00:00.0,24,PROCESSING',
 '2299,2013-08-06 00:00:00.0,25,COMPLETE',
 '9151,2013-09-20 00:00:00.0,25,COMPLETE',
 '32587,2014-02-11 00:00:00.0,25,PENDING_PAYMENT',
 '33227,2014-02-15 00:00:00.0,25,PENDING_PAYMENT',
 '21730,2013-12-05 00:00:00.0,26,CLOSED',
 '26441,2014-01-05 00:00:00.0,26,COMPLETE',
 '30480,2014-01-30 00:00:00.0,26,PENDING',
 '34653,2014-02-23 00:00:00.0,26,COMPLETE',
 '64185,2014-03-28 00:00:00.0,26,PENDING',
 '15906,2013-11-03 00:00:00.0,27,PENDING_PAYMENT',
 '22936,2013-12-13 00:00:00.0,27,CLOSED',
 '29199,2014-01-21 00:00:00.0,27,COMPLETE',
 '36579,2014-03-06 00:00:00.0,27,PENDING_PAYMENT',
 '48721,2014-05-24 00:00:00.0,27,COMPLETE',
 '52772,2014-06-21 00:00:00.0,27,SUSPECTED_FRAUD',
 '56552,2014-07-18 00:00:00.0,27,PENDING',
 '30298,2014-01-29 00:00:00.0,28,PENDING_PAYMENT',
 '30686,2014-01-31 00:00:00.0,28,CLOSED',
 '41673,2014-04-08 00:00:00.0,28,COMPLETE',
 '56885,2014-07-19 00:00:00.0,28,PENDING_PAYMENT',
 '58072,2013-08-06 00:00:00.0,29,CLOSED',
 '34075,2014-02-19 00:00:00.0,29,PENDING_PAYMENT',
 '52951,2014-06-23 00:00:00.0,29,PENDING_PAYMENT',
 '21848,2013-12-06 00:00:00.0,30,PENDING_PAYMENT',
 '37436,2014-03-12 00:00:00.0,30,COMPLETE',
 '6517,2013-09-04 00:00:00.0,31,PENDING_PAYMENT',
 '19966,2013-11-25 00:00:00.0,31,CLOSED',
 '24039,2013-12-21 00:00:00.0,31,PROCESSING',
 '28265,2014-01-15 00:00:00.0,31,SUSPECTED_FRAUD',
 '31933,2014-02-07 00:00:00.0,31,PENDING_PAYMENT',
 '41081,2014-04-03 00:00:00.0,31,PENDING_PAYMENT',
 '240,2013-07-26 00:00:00.0,32,PENDING',
 '243,2013-07-26 00:00:00.0,32,ON_HOLD',
 '36168,2014-03-04 00:00:00.0,32,PROCESSING',
 '38038,2014-03-16 00:00:00.0,32,CLOSED',
 '54837,2014-07-07 00:00:00.0,32,PENDING',
 '1712,2013-08-02 00:00:00.0,33,COMPLETE',
 '23835,2013-12-20 00:00:00.0,33,PENDING',
 '1529,2013-08-01 00:00:00.0,34,ON_HOLD',
 '13682,2013-10-18 00:00:00.0,34,PENDING',
 '13988,2013-10-20 00:00:00.0,34,COMPLETE',
 '16891,2013-11-07 00:00:00.0,34,PENDING_PAYMENT',
 '68096,2014-02-03 00:00:00.0,34,PENDING',
 '42517,2014-04-12 00:00:00.0,34,PROCESSING',
 '50299,2014-06-05 00:00:00.0,34,PENDING_PAYMENT',
 '9110,2013-09-20 00:00:00.0,35,PENDING_PAYMENT',
 '11256,2013-10-02 00:00:00.0,35,CANCELED',
 '18279,2013-11-14 00:00:00.0,35,COMPLETE',
 '49665,2014-05-31 00:00:00.0,35,PROCESSING',
 '4423,2013-08-20 00:00:00.0,36,PROCESSING',
 '28812,2014-01-19 00:00:00.0,36,PROCESSING',
 '65732,2014-05-24 00:00:00.0,36,CLOSED',
 '1896,2013-08-04 00:00:00.0,37,CLOSED',
 '9545,2013-09-23 00:00:00.0,37,COMPLETE',
 '65103,2014-05-01 00:00:00.0,37,CLOSED',
 '8626,2013-09-17 00:00:00.0,38,PROCESSING',
 '27562,2014-01-11 00:00:00.0,38,CLOSED',
 '27812,2014-01-13 00:00:00.0,38,CLOSED',
 '30415,2014-01-30 00:00:00.0,38,PROCESSING',
 '31591,2014-02-05 00:00:00.0,38,CLOSED',
 '54410,2014-07-03 00:00:00.0,38,PROCESSING',
 '18311,2013-11-14 00:00:00.0,39,PROCESSING',
 '61149,2013-12-03 00:00:00.0,39,PROCESSING',
 '25140,2013-12-27 00:00:00.0,39,PROCESSING',
 '28847,2014-01-19 00:00:00.0,39,PROCESSING',
 '44059,2014-04-24 00:00:00.0,39,PENDING_PAYMENT',
 '58440,2013-08-21 00:00:00.0,40,PENDING_PAYMENT',
 '60449,2013-11-07 00:00:00.0,40,PROCESSING',
 '22061,2013-12-07 00:00:00.0,40,CLOSED',
 '29089,2014-01-21 00:00:00.0,40,ON_HOLD',
 '35837,2014-03-02 00:00:00.0,40,PENDING',
 '49341,2014-05-28 00:00:00.0,40,PENDING_PAYMENT',
 '66854,2014-07-04 00:00:00.0,40,COMPLETE',
 '3919,2013-08-17 00:00:00.0,41,PENDING_PAYMENT',
 '67819,2013-11-18 00:00:00.0,41,PROCESSING',
 '24396,2013-12-23 00:00:00.0,41,CLOSED',
 '47303,2014-05-13 00:00:00.0,41,PENDING_PAYMENT',
 '48116,2014-05-19 00:00:00.0,41,COMPLETE',
 '54426,2014-07-03 00:00:00.0,41,PENDING_PAYMENT',
 '6612,2013-09-05 00:00:00.0,42,PENDING_PAYMENT',
 '60228,2013-10-30 00:00:00.0,42,CLOSED',
 '25843,2013-12-31 00:00:00.0,42,PENDING_PAYMENT',
 '28190,2014-01-15 00:00:00.0,42,COMPLETE',
 '34589,2014-02-23 00:00:00.0,42,COMPLETE',
 '46986,2014-05-12 00:00:00.0,42,COMPLETE',
 '52903,2014-06-23 00:00:00.0,42,PENDING_PAYMENT',
 '54267,2014-07-02 00:00:00.0,42,COMPLETE',
 '56155,2014-07-15 00:00:00.0,42,PENDING_PAYMENT',
 '28296,2014-01-15 00:00:00.0,43,PENDING',
 '62428,2014-01-21 00:00:00.0,43,COMPLETE',
 '6485,2013-09-03 00:00:00.0,44,PENDING_PAYMENT',
 '8329,2013-09-14 00:00:00.0,44,COMPLETE',
 '17087,2013-11-08 00:00:00.0,44,PENDING_PAYMENT',
 '19622,2013-11-23 00:00:00.0,44,ON_HOLD',
 '29377,2014-01-22 00:00:00.0,44,PENDING_PAYMENT',
 '55136,2014-07-08 00:00:00.0,44,PROCESSING',
 '253,2013-07-26 00:00:00.0,45,COMPLETE',
 '58714,2013-08-30 00:00:00.0,45,PENDING',
 '12558,2013-10-10 00:00:00.0,45,PENDING',
 '23444,2013-12-18 00:00:00.0,45,CLOSED',
 '62313,2014-01-16 00:00:00.0,45,PENDING_PAYMENT',
 '41071,2014-04-03 00:00:00.0,45,COMPLETE',
 '10983,2013-09-30 00:00:00.0,46,COMPLETE',
 '40169,2014-03-30 00:00:00.0,46,ON_HOLD',
 '42236,2014-04-11 00:00:00.0,46,PROCESSING',
 '46066,2014-05-06 00:00:00.0,46,PROCESSING',
 '53062,2014-06-24 00:00:00.0,46,COMPLETE',
 '34631,2014-02-23 00:00:00.0,47,PENDING_PAYMENT',
 '38645,2014-03-20 00:00:00.0,47,COMPLETE',
 '42605,2014-04-13 00:00:00.0,47,COMPLETE',
 '55620,2014-07-12 00:00:00.0,47,COMPLETE',
 '916,2013-07-30 00:00:00.0,48,PENDING',
 '7700,2013-09-10 00:00:00.0,48,ON_HOLD',
 '13425,2013-10-15 00:00:00.0,48,PROCESSING',
 '18605,2013-11-17 00:00:00.0,48,SUSPECTED_FRAUD',
 '62732,2014-01-29 00:00:00.0,48,PROCESSING',
 '32234,2014-02-09 00:00:00.0,48,COMPLETE',
 '46665,2014-05-10 00:00:00.0,48,PROCESSING',
 '65451,2014-05-12 00:00:00.0,48,COMPLETE',
 '15810,2013-11-03 00:00:00.0,49,SUSPECTED_FRAUD',
 '23388,2013-12-17 00:00:00.0,49,CLOSED',
 '34143,2014-02-19 00:00:00.0,49,PAYMENT_REVIEW',
 '41824,2014-04-09 00:00:00.0,49,PENDING_PAYMENT',
 '5794,2013-08-29 00:00:00.0,50,COMPLETE',
 '11814,2013-10-05 00:00:00.0,50,COMPLETE',
 '60054,2013-10-22 00:00:00.0,50,COMPLETE',
 '24948,2013-12-26 00:00:00.0,50,PROCESSING',
 '41244,2014-04-04 00:00:00.0,50,PENDING',
 '1717,2013-08-02 00:00:00.0,51,PROCESSING',
 '3638,2013-08-15 00:00:00.0,51,CLOSED',
 '58829,2013-09-04 00:00:00.0,51,CLOSED',
 '13138,2013-10-13 00:00:00.0,51,PENDING',
 '16187,2013-11-04 00:00:00.0,51,PAYMENT_REVIEW',
 '24119,2013-12-21 00:00:00.0,51,COMPLETE',
 '27652,2014-01-12 00:00:00.0,51,COMPLETE',
 '50521,2014-06-07 00:00:00.0,51,CLOSED',
 '6440,2013-09-03 00:00:00.0,52,PENDING',
 '12413,2013-10-08 00:00:00.0,52,PENDING_PAYMENT',
 '15463,2013-10-31 00:00:00.0,52,COMPLETE',
 '67794,2013-11-08 00:00:00.0,52,PENDING',
 '38973,2014-03-22 00:00:00.0,52,PAYMENT_REVIEW',
 '13308,2013-10-15 00:00:00.0,53,PENDING',
 '23293,2013-12-16 00:00:00.0,53,PENDING_PAYMENT',
 '24704,2013-12-25 00:00:00.0,53,PENDING',
 '34546,2014-02-23 00:00:00.0,53,CANCELED',
 '36976,2014-03-10 00:00:00.0,53,PENDING_PAYMENT',
 '44585,2014-04-27 00:00:00.0,53,PENDING_PAYMENT',
 '1207,2013-07-31 00:00:00.0,54,SUSPECTED_FRAUD',
 '17162,2013-11-09 00:00:00.0,54,PENDING_PAYMENT',
 '27668,2014-01-12 00:00:00.0,54,PROCESSING',
 '33013,2014-02-14 00:00:00.0,54,COMPLETE',
 '47298,2014-05-13 00:00:00.0,54,PENDING',
 '66482,2014-06-20 00:00:00.0,54,COMPLETE',
 '28216,2014-01-15 00:00:00.0,55,CLOSED',
 '30923,2014-02-01 00:00:00.0,55,PENDING_PAYMENT',
 '38848,2014-03-21 00:00:00.0,55,CLOSED',
 '68348,2014-04-15 00:00:00.0,55,CLOSED',
 '43008,2014-04-17 00:00:00.0,55,PENDING_PAYMENT',
 '65778,2014-05-26 00:00:00.0,55,PENDING_PAYMENT',
 '26671,2014-01-06 00:00:00.0,56,ON_HOLD',
 '31257,2014-02-03 00:00:00.0,56,ON_HOLD',
 '36060,2014-03-03 00:00:00.0,56,PENDING_PAYMENT',
 '43262,2014-04-19 00:00:00.0,56,PENDING_PAYMENT',
 '66386,2014-06-17 00:00:00.0,56,COMPLETE',
 '54232,2014-07-02 00:00:00.0,56,PENDING_PAYMENT',
 '19977,2013-11-25 00:00:00.0,57,ON_HOLD',
 '33056,2014-02-14 00:00:00.0,57,COMPLETE',
 '33261,2014-02-15 00:00:00.0,57,PENDING_PAYMENT',
 '44851,2014-04-28 00:00:00.0,57,COMPLETE',
 '45900,2014-05-06 00:00:00.0,57,COMPLETE',
 '66137,2014-06-09 00:00:00.0,57,PENDING_PAYMENT',
 '117,2013-07-26 00:00:00.0,58,SUSPECTED_FRAUD',
 '9129,2013-09-20 00:00:00.0,58,PENDING',
 '10556,2013-09-28 00:00:00.0,58,PROCESSING',
 '22143,2013-12-07 00:00:00.0,58,PENDING',
 '26057,2014-01-02 00:00:00.0,58,PENDING_PAYMENT',
 '62826,2014-02-03 00:00:00.0,58,CLOSED',
 '35942,2014-03-03 00:00:00.0,58,PENDING_PAYMENT',
 '38201,2014-03-17 00:00:00.0,58,PENDING',
 '57390,2014-07-22 00:00:00.0,58,COMPLETE',
 '29902,2014-01-26 00:00:00.0,59,COMPLETE',
 '36114,2014-03-04 00:00:00.0,59,COMPLETE',
 '43295,2014-04-19 00:00:00.0,59,COMPLETE',
 '44966,2014-04-29 00:00:00.0,59,PENDING',
 '48825,2014-05-24 00:00:00.0,59,PENDING_PAYMENT',
 '50715,2014-06-08 00:00:00.0,59,PENDING_PAYMENT',
 '3647,2013-08-15 00:00:00.0,60,PROCESSING',
 '13777,2013-10-19 00:00:00.0,60,CLOSED',
 '13795,2013-10-19 00:00:00.0,60,COMPLETE',
 '36666,2014-03-06 00:00:00.0,60,PENDING',
 '48059,2014-05-18 00:00:00.0,60,PROCESSING',
 '1144,2013-07-31 00:00:00.0,61,SUSPECTED_FRAUD',
 '1168,2013-07-31 00:00:00.0,61,PENDING_PAYMENT',
 '4690,2013-08-22 00:00:00.0,61,COMPLETE',
 '30287,2014-01-29 00:00:00.0,61,PROCESSING',
 '36210,2014-03-04 00:00:00.0,61,PENDING',
 '4738,2013-08-23 00:00:00.0,62,ON_HOLD',
 '19658,2013-11-23 00:00:00.0,62,ON_HOLD',
 '36809,2014-03-07 00:00:00.0,62,COMPLETE',
 '55819,2014-07-13 00:00:00.0,62,PROCESSING',
 '9484,2013-09-22 00:00:00.0,63,PENDING_PAYMENT',
 '61406,2013-12-13 00:00:00.0,63,COMPLETE',
 '61772,2013-12-26 00:00:00.0,63,CLOSED',
 '33365,2014-02-16 00:00:00.0,63,PENDING',
 '42489,2014-04-12 00:00:00.0,63,COMPLETE',
 '66258,2014-06-13 00:00:00.0,63,COMPLETE',
 '67003,2014-07-09 00:00:00.0,63,COMPLETE',
 '643,2013-07-28 00:00:00.0,64,PENDING_PAYMENT',
 '7889,2013-09-12 00:00:00.0,64,CANCELED',
 '34707,2014-02-24 00:00:00.0,64,SUSPECTED_FRAUD',
 '16078,2013-11-03 00:00:00.0,65,PENDING_PAYMENT',
 '30704,2014-01-31 00:00:00.0,65,PENDING',
 '33962,2014-02-19 00:00:00.0,65,COMPLETE',
 '63659,2014-03-05 00:00:00.0,65,PROCESSING',
 '63847,2014-03-15 00:00:00.0,65,PENDING_PAYMENT',
 '41971,2014-04-09 00:00:00.0,65,PROCESSING',
 '535,2013-07-28 00:00:00.0,66,COMPLETE',
 '1728,2013-08-02 00:00:00.0,66,PENDING_PAYMENT',
 '11714,2013-10-05 00:00:00.0,66,PROCESSING',
 '31644,2014-02-06 00:00:00.0,66,PENDING_PAYMENT',
 '43596,2014-04-21 00:00:00.0,66,COMPLETE',
 '17335,2013-11-09 00:00:00.0,67,PENDING_PAYMENT',
 '61841,2013-12-28 00:00:00.0,67,PENDING_PAYMENT',
 '25722,2013-12-31 00:00:00.0,67,PENDING_PAYMENT',
 '9803,2013-09-24 00:00:00.0,68,PENDING_PAYMENT',
 '19173,2013-11-21 00:00:00.0,68,ON_HOLD',
 '40532,2014-04-01 00:00:00.0,68,SUSPECTED_FRAUD',
 '10999,2013-09-30 00:00:00.0,69,COMPLETE',
 '67766,2013-11-02 00:00:00.0,69,PENDING',
 '21565,2013-12-05 00:00:00.0,69,COMPLETE',
 '62661,2014-01-27 00:00:00.0,69,PROCESSING',
 '34273,2014-02-21 00:00:00.0,69,COMPLETE',
 '42230,2014-04-11 00:00:00.0,69,PENDING',
 '50593,2014-06-07 00:00:00.0,69,COMPLETE',
 '718,2013-07-29 00:00:00.0,70,COMPLETE',
 '6729,2013-09-05 00:00:00.0,70,PENDING',
 '10450,2013-09-27 00:00:00.0,70,PENDING',
 '61036,2013-11-27 00:00:00.0,70,COMPLETE',
 '24457,2013-12-23 00:00:00.0,70,ON_HOLD',
 '68051,2014-01-24 00:00:00.0,70,PENDING',
 '30680,2014-01-31 00:00:00.0,70,COMPLETE',
 '1237,2013-07-31 00:00:00.0,71,PENDING_PAYMENT',
 '4398,2013-08-20 00:00:00.0,71,PENDING',
 '7540,2013-09-09 00:00:00.0,71,PROCESSING',
 '9082,2013-09-20 00:00:00.0,71,COMPLETE',
 '9441,2013-09-22 00:00:00.0,71,CLOSED',
 '15015,2013-10-28 00:00:00.0,71,PENDING_PAYMENT',
 '24148,2013-12-22 00:00:00.0,71,COMPLETE',
 '28967,2014-01-20 00:00:00.0,71,ON_HOLD',
 '38440,2014-03-18 00:00:00.0,71,PROCESSING',
 '65480,2014-05-13 00:00:00.0,71,COMPLETE',
 '6001,2013-08-31 00:00:00.0,72,PENDING_PAYMENT',
 '8286,2013-09-14 00:00:00.0,72,PROCESSING',
 '59109,2013-09-16 00:00:00.0,72,COMPLETE',
 '22017,2013-12-07 00:00:00.0,72,COMPLETE',
 '64084,2014-03-23 00:00:00.0,72,PENDING_PAYMENT',
 '46392,2014-05-09 00:00:00.0,72,PROCESSING',
 '55618,2014-07-12 00:00:00.0,72,PROCESSING',
 '56917,2014-07-20 00:00:00.0,72,PENDING_PAYMENT',
 '10193,2013-09-26 00:00:00.0,73,COMPLETE',
 '19009,2013-11-20 00:00:00.0,73,PROCESSING',
 '21166,2013-12-02 00:00:00.0,73,PENDING_PAYMENT',
 '26461,2014-01-05 00:00:00.0,73,PENDING',
 '29240,2014-01-21 00:00:00.0,73,COMPLETE',
 '49356,2014-05-28 00:00:00.0,73,COMPLETE',
 '2227,2013-08-06 00:00:00.0,74,PENDING',
 '7815,2013-09-11 00:00:00.0,74,ON_HOLD',
 '10020,2013-09-25 00:00:00.0,74,COMPLETE',
 '47114,2014-05-12 00:00:00.0,74,COMPLETE',
 '48938,2014-05-25 00:00:00.0,74,CLOSED',
 '66305,2014-06-14 00:00:00.0,74,CLOSED',
 '57411,2014-07-22 00:00:00.0,74,COMPLETE',
 '3136,2013-08-11 00:00:00.0,75,CLOSED',
 '5847,2013-08-29 00:00:00.0,75,PENDING_PAYMENT',
 '8035,2013-09-12 00:00:00.0,75,PENDING_PAYMENT',
 '8939,2013-09-19 00:00:00.0,75,COMPLETE',
 '32287,2014-02-09 00:00:00.0,75,PENDING',
 '63601,2014-03-04 00:00:00.0,75,COMPLETE',
 '52764,2014-06-21 00:00:00.0,75,COMPLETE',
 '324,2013-07-26 00:00:00.0,76,COMPLETE',
 '394,2013-07-27 00:00:00.0,76,PENDING_PAYMENT',
 '38850,2014-03-21 00:00:00.0,76,COMPLETE',
 '41843,2014-04-09 00:00:00.0,76,PENDING_PAYMENT',
 '48135,2014-05-19 00:00:00.0,76,PENDING_PAYMENT',
 '16836,2013-11-07 00:00:00.0,77,COMPLETE',
 '62014,2014-01-05 00:00:00.0,77,PENDING_PAYMENT',
 '28857,2014-01-19 00:00:00.0,77,PENDING',
 '32601,2014-02-11 00:00:00.0,77,COMPLETE',
 '34142,2014-02-19 00:00:00.0,77,COMPLETE',
 '68532,2014-06-06 00:00:00.0,77,CLOSED',
 '55501,2014-07-11 00:00:00.0,77,PROCESSING',
 '56674,2014-07-18 00:00:00.0,77,COMPLETE',
 '57183,2014-07-21 00:00:00.0,77,PENDING',
 '41076,2014-04-03 00:00:00.0,78,COMPLETE',
 '42513,2014-04-12 00:00:00.0,78,COMPLETE',
 '10735,2013-09-29 00:00:00.0,79,PENDING_PAYMENT',
 '60459,2013-11-07 00:00:00.0,79,PROCESSING',
 '21798,2013-12-06 00:00:00.0,79,PENDING',
 '25645,2013-12-31 00:00:00.0,79,PENDING_PAYMENT',
 '26738,2014-01-06 00:00:00.0,79,COMPLETE',

* Create a collection of order_items by reading data from a file.

In [29]:
order_items_path = "/data/retail_db/order_items/part-00000"
order_items = open(order_items_path). \
    read(). \
    splitlines()

* Get revenue for a given order_item_order_id.

In [30]:
def get_order_revenue(order_items, order_id):
    order_items_filtered = filter(lambda oi: 
                                  int(oi.split(",")[1]) == 2, 
                                  order_items
                                 )
    order_items_map = map(lambda oi: 
                          float(oi.split(",")[4]), 
                          order_items_filtered
                         )
    return round(sum(order_items_map), 2)

In [31]:
get_order_revenue(order_items, 2)

579.98

## Overview of Pandas Data Frames

While collections are typically the group of objects or tuples or simple strings, we need to parse them to further process the data. This process is tedious at times.
* With Data Frames we can define the structure.
* Data Frame is nothing but group of rows where each row have multiple attributes with names.
* Data Frame is similar to a Database Table or Spreadsheet with Header.
* Pandas provide rich and simple functions to convert data in files into Data Frames and process them
* Data can be read from files into Data Frame using functions such as read_csv.
* We can perform all standard operations on Data Frames.
  * Projection or Selection     
  * Filtering     
  * Aggregations     
  * Joins     
  * Sorting

### Tasks

Let us perform few tasks to recap the usage of Pandas Data Frames.
    
* Read order items data from the location on your system. In mine it is /data/retail_db/order_items/part-00000. Use the information below to define schema.
* It has 6 fields with the below names in the same order as specified below.
  * order_item_id
  * order_item_order_id
  * order_item_product_id
  * order_item_quantity
  * order_item_subtotal
  * order_item_product_price

In [32]:
import pandas as pd
order_items_path = "/data/retail_db/order_items/part-00000"
order_items = pd. \
    read_csv(order_items_path,
             names=["order_item_id", "order_item_order_id",
                    "order_item_product_id", "order_item_quantity",
                    "order_item_subtotal", "order_item_product_price"
                   ]
            )

* Project order_item_order_id and order_item_subtotal

In [33]:
order_items[["order_item_id", "order_item_subtotal"]]

        order_item_id  order_item_subtotal
0                   1               299.98
1                   2               199.99
2                   3               250.00
3                   4               129.99
4                   5                49.98
...               ...                  ...
172193         172194               129.99
172194         172195                59.99
172195         172196                50.00
172196         172197              1999.99
172197         172198               150.00

[172198 rows x 2 columns]

* Filter for order_item_order_id 2

In [34]:
order_items.query("order_item_order_id == 2")

,order_item_id,order_item_order_id,order_item_product_id,order_item_quantity,order_item_subtotal,order_item_product_price
1,2,2,1073,1,199.99,199.99
2,3,2,502,5,250.00,50.00
3,4,2,403,1,129.99,129.99

* Compute revenue for order_item_order_id 2

In [35]:
order_items. \
    query("order_item_order_id == 2")["order_item_subtotal"]. \
    sum()

579.98

* Get number of items and revenue for each order id. Give alias to the order revenue as **revenue**.

In [36]:
order_items. \
    groupby("order_item_order_id")["order_item_subtotal"]. \
    sum()

order_item_order_id
1         299.98
2         579.98
4         699.85
5        1129.86
7         579.92
          ...
68879    1259.97
68880     999.77
68881     129.99
68882     109.99
68883    2149.99
Name: order_item_subtotal, Length: 57431, dtype: float64

In [37]:
order_items. \
    groupby("order_item_order_id")["order_item_subtotal"]. \
    agg(['sum', 'count']). \
    rename(columns={'sum': 'revenue'})

                     revenue  count
order_item_order_id
1                     299.98      1
2                     579.98      3
4                     699.85      4
5                    1129.86      5
7                     579.92      3
...                      ...    ...
68879                1259.97      3
68880                 999.77      5
68881                 129.99      1
68882                 109.99      2
68883                2149.99      2

[57431 rows x 2 columns]

## Limitations of Pandas

We can use Pandas for data processing. It provides rich APIs to read data from different sources, process the data and then write it to different targets.
* Pandas works well for light weight data processing.
* Pandas is typically single threaded, which means only one process take care of processing the data.
* As data volume grows, the processing time might grow exponentially and also run into resource contention.
* It is not trivial to use distributed processing using Pandas APIs. We will end up struggling with multi threading rather than business logic.
* There are Distributed Computing Frameworks such as Hadoop Map Reduce, Spark etc to take care of data processing at scale on multi node Hadoop or Spark Clusters.
* Both Hadoop Map Reduce and Spark comes with Distributed Computing Frameworks as well as APIs.

**Pandas is typically used for light weight Data Processing and Spark is used for Data Processing at Scale.**

## Development Life Cycle

Let us understand the development life cycle. We typically use IDEs such as PyCharm to develop Python based applications.

* Create Project - retail
* Choose the interpreter 3.x
* Make sure plugins such as pandas are installed.
* Create config.py script for externalizing run time parameters such as input path, output path etc.
* Create app folder for the source code.

### Tasks

Let us develop a simple application to understand end to end development life cycle.

* Read the data from order_items
* Get revenue for each order id
* Save the output which contain order id and revenue to a file.

Click [here](https://github.com/dgadiraju/python-retail/tree/v1.0) for the complete code for the above tasks.

## Exercises

Let us perform few exercises to understand how to process the data. We will use LinkedIn data to perform some basic data processing using Python.

* Get LinkedIn archive.
  * Go to https://linkedin.com
  * Me on top -> Settings & Privacy
  * Then go to "How LinkedIn users your data" -> Getting a copy of your data
  * Register and download. You will get a link as part of the email.
* Data contain multiple CSV files. We will limit the analysis to **Contacts.csv** and **Connections.csv**.
* Get the number of **contacts** with out email ids.
* Get the number of **contacts** from each source.
* Get the number of **connections** with each title.
* Get the number of **connections** from each company.
* Get the number of **contacts** for each month in the year 2018.
* Use Postgres or MySQL as databases (you can setup in your laptop) and write **connections** data to the database